network:
  ip: 127.0.0.1
  port: 5005

global:
  participant_id: "participant_default"
  session_id: "session_001"

m1_task:
  controller: keyboard  # or 'bluetooth_joystick'
  joystick_device: ""   # e.g., /dev/tty.* or leave blank for default
  repetitions: 3
  sequence: ['4', '1', '3', '2', '4']  # Tapping sequence
  sequence_display_time: 1  # Time in seconds to show the sequence
  randomize_sequence: true # true to shuffle the sequence each repetition
  response_cutoff_time: 5 # Add this! (e.g., 5 seconds for the response phase)

v1_task:
  stimulus_duration: 0.1 # Duration in seconds for how long the grating stimulus is shown
  n_trials: 20 # Added example
  response_cutoff_time: 3 # Example: 3 seconds for response cutoff

ei_task:
  # Uses network.ip and network.port from the global network config by default
  # Specific overrides can be placed here if needed, e.g.:
  # network_ip: "127.0.0.1"
  # network_port: 5005 
  initial_radius_pix: 50      # Initial radius of the circle in pixels
  circle_fill_color: 'cyan'   # Fill color of the circle
  circle_line_color: 'white'  # Border color of the circle
  data_timeout_seconds: 10    # Seconds of no data before client is considered timed out
  text_color: 'white'
  text_height_pix: 20
  debug_mode: false           # Set to true for more verbose logging from ei_display_task (if implemented)

# FSL-MRS LSL Configuration
fsl_mrs_lsl:
  stream_name: 'FSL-MRS-EI-Ratio'
  stream_type: 'EI_Ratio'
  source_id: 'fsl-mrs-ei-001'
  sampling_rate: 1.0  # Hz
  simulation_mode: true  # Set to false when using real FSL-MRS
  simulation_range: [0.3, 1.2]  # Min/max E/I ratio values (fallback)
  simulation_noise: 0.05  # Noise level for basic simulation (fallback)
  
  # Advanced MRS data generator settings
  mrs_noise_level: 0.03  # Noise level for realistic MRS simulation
  mrs_temporal_variation: 0.1  # Temporal variation magnitude
  mrs_drift_enabled: true  # Enable temporal drift simulation
  mrs_physiological_constraints: true  # Apply physiological constraints
  mrs_spectrum_simulation: true  # Generate full MRS spectra

# FSL-MRS Configuration
fsl_mrs:
  data_path: null  # Path to MRS data files
  basis_set_path: null  # Path to basis set files
  fitting_params:
    # FSL-MRS fitting parameters would go here
    # These depend on the specific FSL-MRS API

# LSL E/I Receiver Configuration
lsl_ei_receiver:
  stream_name: 'FSL-MRS-EI-Ratio'
  stream_type: 'EI_Ratio'
  source_id: null  # null means any source
  forward_host: '127.0.0.1'
  forward_port: 5005
  forward_enabled: true
  connection_retry_interval: 5.0  # seconds
  stream_resolve_timeout: 5.0  # seconds
  buffer_length: 360  # seconds
  max_chunk_length: 0  # 0 = no chunking
